<?php

namespace App\Services;

use App\Models\Reseller;
use App\Support\ResellerDomain;

/**
 * Keeps Traefik's picture of reseller custom domains true to the database.
 *
 * The proxy only routes hostnames it has been told about, and it was only ever told
 * about the platform's own — so a verified custom domain pointed perfectly at this
 * server still died at the front door with a 503 and no certificate. This writes one
 * small router file per verified domain into the folder Traefik's file provider
 * watches (`providers.file.watch=true`): route http to https, terminate https with a
 * certificate from the HTTP-01 resolver, hand the request to the app. Issuance
 * happens the moment the domain's DNS actually reaches us, renewal is Traefik's
 * problem, and no proxy restart, redeploy or dashboard click is involved.
 *
 * Everything here is derived state, synced by the scheduler each minute: removing a
 * domain removes its file, and the whole folder can be deleted and regenerated.
 * The service URL is the compose service's stable network alias (`app`), which
 * coolify-proxy shares a network with — container names change every deploy, the
 * alias does not.
 */
class CustomDomainProxySync
{
    /**
     * @return array{written: int, removed: int, kept: int}|null null when no directory
     *                                                           is configured (dev) or it is missing (mount absent).
     */
    public function sync(): ?array
    {
        $dir = (string) config('proxy.custom_domains_dir');

        if ($dir === '' || ! is_dir($dir)) {
            return null;
        }

        // The platform's own hosts and subdomain space are routed by the proxy's
        // existing configuration; a reseller row must never be able to shadow them.
        $never = ResellerDomain::platformHosts(parse_url((string) config('app.url'), PHP_URL_HOST));
        $base = strtolower((string) config('reseller.domain'));

        $wanted = [];

        Reseller::query()
            ->whereNotNull('custom_domain')
            ->where('custom_domain_status', Reseller::DOMAIN_VERIFIED)
            ->pluck('custom_domain')
            ->each(function (string $domain) use (&$wanted, $never, $base) {
                $domain = strtolower(trim($domain));

                $offLimits = $domain === ''
                    || in_array($domain, $never, true)
                    || $domain === $base
                    || str_ends_with($domain, '.'.$base)
                    // Belt and braces on top of the input validation: this string is
                    // about to be written into proxy configuration.
                    || ! preg_match('/^[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?)+$/', $domain);

                if (! $offLimits) {
                    // Prefixed because the folder is Traefik's whole dynamic-config dir
                    // (its file provider does not descend into subdirectories), shared
                    // with files Coolify writes. The prefix is both our namespace and
                    // the only pattern the cleanup below is allowed to delete.
                    $wanted['custom-domain-'.$domain.'.yaml'] = $this->routerYaml($domain);
                }
            });

        $written = $kept = $removed = 0;

        foreach ($wanted as $file => $content) {
            $path = $dir.DIRECTORY_SEPARATOR.$file;
            if (is_file($path) && file_get_contents($path) === $content) {
                $kept++;

                continue;
            }
            file_put_contents($path, $content);
            $written++;
        }

        foreach (glob($dir.DIRECTORY_SEPARATOR.'custom-domain-*.yaml') ?: [] as $existing) {
            if (! array_key_exists(basename($existing), $wanted)) {
                unlink($existing);
                $removed++;
            }
        }

        return ['written' => $written, 'removed' => $removed, 'kept' => $kept];
    }

    /**
     * Routers for the domain and its www form. Two separate https routers on purpose:
     * Traefik orders one certificate per router covering every host in its rule, and
     * a reseller who pointed the apex but never created the www record would fail the
     * whole combined order — two routers means the apex certificate succeeds alone,
     * and www simply starts working (the app 301s it to the bare domain) whenever its
     * record appears.
     */
    private function routerYaml(string $domain): string
    {
        $slug = str_replace('.', '-', $domain);

        return <<<YAML
# Generated by CustomDomainProxySync — do not edit; the scheduler rewrites this file.
http:
  routers:
    custom-{$slug}-https:
      rule: Host(`{$domain}`)
      entryPoints:
        - https
      service: custom-domains-app@file
      middlewares:
        - gzip@docker
      tls:
        certResolver: letsencrypt
    custom-{$slug}-www-https:
      rule: Host(`www.{$domain}`)
      entryPoints:
        - https
      service: custom-domains-app@file
      middlewares:
        - gzip@docker
      tls:
        certResolver: letsencrypt
    custom-{$slug}-http:
      rule: Host(`{$domain}`) || Host(`www.{$domain}`)
      entryPoints:
        - http
      service: custom-domains-app@file
      middlewares:
        - redirect-to-https@docker
  services:
    custom-domains-app:
      loadBalancer:
        servers:
          - url: http://app:8080

YAML;
    }
}
