<?php

namespace App\Reports;

use App\Models\User;
use App\Reports\Contracts\Report;
use Illuminate\Support\LazyCollection;
use Illuminate\Support\Str;

/**
 * A report, run. Everything the three exporters need and nothing they don't.
 */
final class ReportResult
{
    public function __construct(
        public readonly Report $report,
        public readonly ReportFilters $filters,
        /** @var ReportColumn[] */
        public readonly array $columns,
        /** @var ReportStat[] */
        public readonly array $stats,
        /** @var LazyCollection<int, array<string, mixed>> */
        public readonly LazyCollection $rows,
        public readonly int $total,
        public readonly ReportBranding $branding,
        public readonly ?User $generatedBy = null,
    ) {}

    /**
     * The header block printed on every export and shown above every on-screen report.
     *
     * Present on all three formats deliberately: a downloaded file with no date range, no
     * scope and no generated-at is unciteable a month later, and someone will forward it.
     *
     * @return array<string, string>
     */
    public function header(): array
    {
        return array_filter([
            'Report' => $this->report->title(),
            'Scope' => $this->branding->scopeLabel,
            'Period' => $this->report->usesDateWindow() ? $this->filters->label() : 'As of now',
            'Counted by' => $this->report->usesDateWindow() ? $this->report->dateWindowNote() : null,
            'Rows' => number_format($this->total),
            'Generated' => now()->format('j M Y, H:i'),
            'Generated by' => $this->generatedBy
                ? $this->generatedBy->name.' ('.$this->generatedBy->email.')'
                : null,
        ], fn ($value) => $value !== null && $value !== '');
    }

    /**
     * Download filename, without extension. Scoped by owner so a reseller's file is not
     * called "forever-…" — they forward these to families under their own name.
     */
    public function filename(): string
    {
        return Str::slug(implode('-', array_filter([
            $this->branding->filePrefix,
            $this->report->key(),
            $this->report->usesDateWindow() ? $this->filters->slug() : now()->format('Y-m-d'),
        ])));
    }
}
