<?php

use App\Models\Memorial;
use App\Models\PaymentOrder;
use App\Models\SubscriptionPlan;
use App\Models\User;
use App\Reports\ReportRegistry;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Testing\TestResponse;
use Spatie\Permission\Models\Role;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\StreamedResponse;

uses(RefreshDatabase::class);

function reportsAdmin(string $role = 'admin'): User
{
    Role::findOrCreate($role, 'web');

    $admin = User::factory()->create();
    $admin->assignRole($role);

    return $admin;
}

function reportsOrder(array $attributes = []): PaymentOrder
{
    $customer = User::factory()->create();

    $plan = SubscriptionPlan::create([
        'name' => 'Remembrance', 'slug' => 'remembrance-'.uniqid(),
        'price' => 50000, 'interval' => 'year', 'is_active' => true,
    ]);

    $memorial = Memorial::create([
        'user_id' => $customer->id,
        'slug' => 'mary-'.substr(uniqid(), -8),
        'title' => 'In Loving Memory of Mary',
        'full_name' => 'Mary Nakamya',
        'status' => Memorial::STATUS_ACTIVE,
    ]);

    // created_at is not fillable, so back-dating an order has to be forced after the
    // insert — passing it to create() is silently dropped and every order lands today.
    $createdAt = $attributes['created_at'] ?? null;
    unset($attributes['created_at']);

    $order = PaymentOrder::create(array_merge([
        'user_id' => $customer->id,
        'memorial_id' => $memorial->id,
        'subscription_plan_id' => $plan->id,
        'merchant_reference' => 'REF-'.strtoupper(substr(uniqid(), -10)),
        'amount' => 50000,
        'currency' => 'UGX',
        'status' => 'completed',
        'paid_at' => now(),
        'payment_gateway' => 'pesapal',
    ], $attributes));

    if ($createdAt) {
        $order->forceFill(['created_at' => $createdAt])->save();
    }

    return $order;
}

/**
 * The three exporters legitimately return three different response types — CSV streams,
 * xlsx sends a temp file, dompdf returns an in-memory body. The assertions care about the
 * bytes, not the transport.
 */
function reportBody(TestResponse $response): string
{
    $base = $response->baseResponse;

    if ($base instanceof StreamedResponse) {
        return $response->streamedContent();
    }

    if ($base instanceof BinaryFileResponse) {
        return (string) file_get_contents($base->getFile()->getPathname());
    }

    return (string) $base->getContent();
}

it('shows the report catalogue to an admin', function () {
    reportsOrder();

    $this->actingAs(reportsAdmin())
        ->get('/reports')
        ->assertOk()
        ->assertSee('Revenue');
});

it('keeps the catalogue away from ordinary users', function () {
    Role::findOrCreate('user', 'web');
    $user = User::factory()->create();
    $user->assignRole('user');

    $this->actingAs($user)->get('/reports')->assertForbidden();
});

it('renders a report with its rows', function () {
    reportsOrder();

    $this->actingAs(reportsAdmin())
        ->get('/reports/revenue')
        ->assertOk()
        ->assertSee('Mary Nakamya')
        ->assertSee('Gross collected');
});

it('404s an unknown report key rather than erroring', function () {
    $this->actingAs(reportsAdmin())->get('/reports/not-a-report')->assertNotFound();
});

it('narrows rows to the selected date window', function () {
    reportsOrder(['created_at' => now()->subMonths(6), 'paid_at' => now()->subMonths(6)]);

    // The order is six months old, so a 30-day window must not contain it.
    $this->actingAs(reportsAdmin())
        ->get('/reports/revenue?preset=30d')
        ->assertOk()
        ->assertDontSee('Mary Nakamya');

    $this->actingAs(reportsAdmin())
        ->get('/reports/revenue?preset=all')
        ->assertOk()
        ->assertSee('Mary Nakamya');
});

it('downloads a csv with the header block and the rows', function () {
    reportsOrder();

    $response = $this->actingAs(reportsAdmin())->get('/reports/revenue/download/csv');

    $response->assertOk();
    expect($response->headers->get('content-type'))->toContain('text/csv');

    $body = reportBody($response);
    expect($body)->toContain('Mary Nakamya')
        ->toContain('Gross collected')
        ->toContain('Generated by');
});

it('downloads a real xlsx file', function () {
    reportsOrder();

    $response = $this->actingAs(reportsAdmin())->get('/reports/revenue/download/xlsx');

    $response->assertOk();
    expect($response->headers->get('content-type'))
        ->toContain('spreadsheetml');

    // xlsx is a zip container; the magic bytes prove we produced one rather than an
    // error page with a spreadsheet content-type stapled to it.
    expect(substr(reportBody($response), 0, 2))->toBe('PK');
});

it('downloads a real pdf file', function () {
    reportsOrder();

    $response = $this->actingAs(reportsAdmin())->get('/reports/revenue/download/pdf');

    $response->assertOk();
    expect(substr(reportBody($response), 0, 4))->toBe('%PDF');
});

it('rejects a format that is not one of the three', function () {
    $this->actingAs(reportsAdmin())->get('/reports/revenue/download/exe')->assertNotFound();
});

it('neutralises formula injection in csv cells', function () {
    $order = reportsOrder();
    $order->memorial->update(['full_name' => '=cmd|calc!A1']);

    $body = reportBody(
        $this->actingAs(reportsAdmin())->get('/reports/revenue/download/csv')
    );

    // Prefixed with an apostrophe, so Excel treats it as text rather than executing it.
    expect($body)->toContain("'=cmd|calc!A1");
});

it('groups money by currency instead of summing across it', function () {
    reportsOrder(['currency' => 'UGX', 'amount' => 1000]);
    reportsOrder(['currency' => 'USD', 'amount' => 25]);

    $this->actingAs(reportsAdmin())
        ->get('/reports/revenue?preset=all')
        ->assertOk()
        ->assertSee('UGX 1,000')
        ->assertSee('USD 25');
});

it('renders every admin report without erroring', function () {
    reportsOrder();

    $admin = reportsAdmin('super-admin');

    // Walks the registry rather than a hardcoded list, so a report added later is covered
    // the day it is registered instead of the day someone remembers to add a test.
    $reports = app(ReportRegistry::class)
        ->for(ReportRegistry::AUDIENCE_ADMIN, $admin);

    expect($reports)->not->toBeEmpty();

    foreach ($reports as $report) {
        $this->actingAs($admin)
            ->get('/reports/'.$report->key().'?preset=all')
            ->assertOk();
    }
});

it('hides the reseller-program reports from a plain admin', function () {
    $admin = reportsAdmin('admin');

    $keys = app(ReportRegistry::class)
        ->for(ReportRegistry::AUDIENCE_ADMIN, $admin)
        ->map->key();

    expect($keys)->not->toContain('reseller-roster')
        ->not->toContain('reseller-billing');

    $this->actingAs($admin)->get('/reports/reseller-billing')->assertNotFound();
});
